CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE accounts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE invites (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255),
    expiration_date DATE,
    account_id      BIGINT NOT NULL,
    CONSTRAINT fk_invites_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);
