CREATE TABLE memberships (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    CONSTRAINT fk_memberships_account   FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_memberships_user      FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT uq_memberships_account_user UNIQUE (account_id, user_id)
);
