CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    client_side BOOLEAN      NOT NULL DEFAULT FALSE,
    account_id  BIGINT       NOT NULL,
    CONSTRAINT fk_projects_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);
