CREATE TABLE todos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    completed    BOOLEAN      NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP    NULL,
    due_date     DATE         NULL,
    assignee_id  BIGINT       NULL,
    project_id   BIGINT       NOT NULL,
    CONSTRAINT fk_todos_assignee FOREIGN KEY (assignee_id) REFERENCES users (id),
    CONSTRAINT fk_todos_project  FOREIGN KEY (project_id)  REFERENCES projects (id)
);
