CREATE TABLE project_memberships (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_pm_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT uq_pm_project_user UNIQUE (project_id, user_id)
);
